apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  labels:
    app: appointment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
      - name: appointment-service
        image: appointment-service:latest
        imagePullPolicy: Never # Adjust if pushing to a registry
        ports:
        - containerPort: 5004
        env:
        - name: PORT
          value: "5004"
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/healthcare_doctors"
        - name: DOCTOR_SERVICE_URL
          value: "http://doctor-service:5003/api/doctors"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: shcs-jwt
              key: JWT_SECRET
