apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: telemedicine-service:latest
          ports:
            - containerPort: 5003
          env:
            - name: PORT
              value: "5003"
            - name: MONGO_URI
              value: "mongodb+srv://rageeshan0730_db_user:gPzmwFHHGBMa7P5t@dsassignment.negpwzu.mongodb.net/telemedicine_db?appName=DSAssignment"
            - name: RABBITMQ_URI
              value: "amqp://rabbitmq:5672"
